#Python Imports
import pdb
from abc import ABC, abstractmethod
from datetime import datetime

#JPL Imports
from jpl_time import Time

#This Library Imports
from tts_data_utils.core.data_container import DataContainer
from tts_data_utils.core.data_item import DataItem

class ExpectedLadItem(DataItem):
    """
    A specialized DataItem defining the "Golden State" for a telemetry channel.

    **The Concept:**
    In automated mission analysis, knowing the current value (LAD) of a channel 
    is only half the battle. We also need to know what that value *should* be. 
    An `ExpectedLadItem` acts as a requirements record or a "truth" item.

    **How it works:**
    It pairs a `Channel ID` with an `Expected Value` and a `Condition` (e.g., '==', 
    '>', 'within tolerance'). When a telemetry report is generated, the system 
    compares the `Actual Value` against these criteria to automatically generate 
    headlines and disposition messages for operators.

    **Disposition Logic:**
    The item includes fields for "Headline (True)" and "Headline (False)". This 
    allows the software to instantly draft a status report: if the condition 
    is met, it uses the "True" text; if not, it uses the "False" text to flag 
    the discrepancy.

    :param Group: Logical grouping for the measurement (e.g., 'Power', 'Thermal').
    :param Channel ID: The telemetry mnemonic identifier.
    :param Display Name: A human-readable label for the channel.
    :param Data Type: The expected Python or Telemetry data type.
    :param Expected Value: The baseline value used for comparison.
    :param Condition: The mathematical logic used for evaluation (e.g., 'GT', 'LT', 'EQ').
    :param Tolerance: Acceptable variance for numerical comparisons.
    :param Headline (True): Text to display if the actual value matches the expected state.
    :param Disposition Message (True): Detailed explanation for a "Pass" state.
    :param Headline (False): Text to display if the actual value violates the condition.
    :param Disposition Message (False): Detailed explanation for a "Fail" state.
    :param Derivation Handling: Instructions on how to calculate or pull the actual value.
    :param Disposition Handling: Instructions on how to process the pass/fail result.
    :param Actual Value: The real-time measurement pulled from the latest telemetry.
    :param Measurement Time: The timestamp associated with the actual measurement.
    """

    #these are the fields that will be validated against these
    #data types. 

    DICT_VALID_KEYS = [
        ('Group', str),
        ('Channel ID', str),
        ('Display Name', str),
        ('Data Type', str),
        ('Expected Value', (int, float, str, None)),
        ('Condition', str),
        ('Tolerance', (int, float, str, None)),
        ('Headline (True)', (str, None)),
        ('Disposition Message (True)', (str, None)),
        ('Headline (False)', (str, None)),
        ('Disposition Message (False)', (str, None)),
        ('Derivation Handling', (str, None)),
        ('Disposition Handling', (str, None)),
        ('Actual Value', (int, float, str, None)),
        ('Measurement Time', (str, None))
        ]

    TIME_FORMATS = {
    }
    NAME = 'Expected LAD Item'


    @property
    def default_html_row_style(self):
        """Returns row-level CSS styling (defaults to empty)."""
        return {}
    
    @property
    def time(self):
        """The SCET timestamp associated with the expectation or measurement."""
        #TO DO: Figure out path forward
        #that can use JPL Time or not
        return self.source['scet']
        return Time(self.source['scet'])

    @property
    def time_str(self):
        """String representation of the measurement timestamp."""
        #TO DO: Figure out path forward
        #that can use JPL Time or not
        #TO DO: consider making this NOT a property so we can pass
        #different time formats in
        return datetime.strftime(self.source['scet'], self.TIME_FORMATS['scet'])
        return Time(self.source['scet'])

    @property
    def name(self):
        """The channel identifier."""
        return self.source['name']

    @property
    def message(self):
        """The result message generated by the comparison."""
        return self.source['message']

    @property
    def level(self):
        """The severity level associated with this check."""
        return self.source['level']

    def is_warning(self):
        """Returns True if the check result represents a warning or fatal state."""
        return self.level in ['WARNING_LO', 'WARNING_HI', 'FATAL']


class ExpectedLadContainer(DataContainer):
    """
    A collection of ExpectedLadItems, representing a full "Master Comparison List."

    **The Concept:**
    This container is typically loaded from a spreadsheet or a database containing 
    the "Success Criteria" for a specific mission phase (e.g., Launch, Entry, 
    Descent, and Landing). 

    

    **Usage Note:**
    When paired with an `EhaContainer`, this container allows the `InvulnerableDataManager` 
    to perform "Self-Correcting" or "Auto-Auditing" reports, comparing real-time 
    telemetry against these predefined requirements.
    """
    NAME = 'Expected LAD'
    DATA_ITEM_CLS = ExpectedLadItem
    
    def __init__(self, raw_data=None, metadata=None, name=None, nogaps=False, cast_fields=False, **kwargs):
        #TO DO; Clean this up. Shouldn't be checking for a string like this
        #and need to clean up at a higher level
        if metadata is not None:
            metadata = {k:v for k, v in metadata.items() if k[0] != '_' and k != 'dictionary'}
        super().__init__(raw_data=raw_data, metadata=metadata, cast_fields=cast_fields, **kwargs)
        self.name = 'Expected LAD' if name is None else name
        self._repr_cols = [x for x, _ in self.DATA_ITEM_CLS.DICT_VALID_KEYS]
        self._csv_cols = [x for x, _ in self.DATA_ITEM_CLS.DICT_VALID_KEYS]

    def _impl_init(self):
        """Internal initialization hook."""
        return

    @property
    def repr_cols(self):
        """The list of columns intended for display in reports."""
        return self._repr_cols

    @property
    def default_time_label(self):
        """The default time key used for sorting."""
        return self._default_time_label