import pdb
from abc import ABC, abstractmethod

from tts_data_utils.core.data_container import DataContainer
from tts_data_utils.core.data_item import DataItem

from jpl_time import Time

class DiffItem(DataItem):
    """
    An individual record representing a field-level comparison between two objects.

    **The Concept:**
    Think of a `DiffItem` as a single row in a "Spot the Difference" report. It 
    doesn't just store a value; it stores the value from the "Left" side, the 
    value from the "Right" side, and a pre-calculated verdict on whether they 
    are identical.

    **How it works:**
    When two `DataContainers` are compared, each shared key is packed into a 
    `DiffItem`. If the data types differ between the sides (e.g., comparing a 
    string to an integer), the `Type` field is automatically set to "various" 
    to alert the user of a schema mismatch.

    :param Key: Name of the attribute or field being compared.
    :type Key: str
    :param Same: A boolean flag indicating if Left and Right values match.
    :type Same: bool
    :param Type: The Python data type of the values (or "various").
    :type Type: str
    :param Left: The value found in the original (baseline) container.
    :type Left: int | float | str | None
    :param Right: The value found in the comparison (target) container.
    :type Right: int | float | str | None
    """
    DICT_VALID_KEYS = [
        ('Key', str), 
        ('Same', bool), 
        ('Type', str), 
        ('Left', (int, float, str, None)), 
        ('Right', (int, float, str, None))
        ]

    TIME_FORMATS = {}

    # Metadata mapping to prevent infinite recursion during diff operations
    DO_NOT_DIFF = {'source': ['left', 'right']}

    def __sub_init(self):
        """
        Internal initialization hook.
        """
        return

    def time(self):
        """
        [Disabled] 
        
        DiffItems represent logical differences rather than temporal events, 
        so time parsing is disabled by default.
        """
        return


class DiffContainer(DataContainer):
    """
    The results object generated by a `DataContainer.diff()` operation.

    **The Concept:**
    A `DiffContainer` is a specialized collection that holds `DiffItems`. Its 
    primary purpose is to act as a "Filterable Report." By default, when you 
    print or view this container, it filters itself to show only the 
    differences (`Same == False`), allowing you to ignore identical data 
    and focus on what changed.

    **Usage Note:**
    You generally do not instantiate this class manually. It is returned 
    automatically when you call `.diff()` on any standard `DataContainer`.

    :param name: The identifier for this diff report.
    :type name: str
    :param metadata: Contextual information about the two containers being compared.
    :type metadata: dict
    :param csv_path: Optional path to load/save the diff results.
    :type csv_path: str, optional
    """
    NAME = 'diff'
    DATA_ITEM_CLS = DiffItem
    DO_NOT_DIFF = ['left', 'right']

    def __init__(self, name, metadata, csv_path=None):
        super().__init__(csv_path=csv_path)
        self.name = name
        self.metadata = metadata
        self._repr_cols = [x for x, _ in self.DATA_ITEM_CLS.DICT_VALID_KEYS]
        self._csv_cols = [x for x, _ in self.DATA_ITEM_CLS.DICT_VALID_KEYS]
        
        # Default view: Only show rows where a difference was detected
        self._repr_filters = [{'operator': 'eq', 'key': 'Same', 'value': False}]


    def _find_row_by_key(self, key):
        """
        Internal helper to locate a specific comparison row.
        """
        record = [r for r in self.records if r['Key'] == key]
        if len(record) != 1: raise Exception(f'No key "{key}" found.')
        return record[0]

    def left(self, key):
        """
        Retrieves the baseline value for a specific key.

        :param key: The field name to look up.
        :type key: str
        :return: The value from the 'Left' side of the comparison.
        """
        return self._find_row_by_key(key)['left']

    def right(self, key):
        """
        Retrieves the comparison value for a specific key.

        :param key: The field name to look up.
        :type key: str
        :return: The value from the 'Right' side of the comparison.
        """
        return self._find_row_by_key(key)['right']

    def is_same(self):
        """
        Filters the report to show only matching records.

        **Concept:**
        Useful for "sanity checking" to confirm which values were verified 
        as identical.
        """
        return self.eq('Same', True)

    def not_same(self):
        """
        Filters the report to show only mismatched records.

        **Concept:**
        This is the primary troubleshooting view, isolating only the 
        discrepancies between datasets.
        """
        return self.eq('Same', False)

    @property
    def repr_cols(self):
        """
        Returns the standard list of columns for display.
        """
        return self._repr_cols